version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: demo-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

        backend:
    build: ./backend
    container_name: demo-backend
    restart: always
    depends_on:
      - postgres
    environment:
      PORT: 5001
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: docker
      DB_HOST: postgres      # service name → backend can talk to postgres
      DB_PORT: 5432
      JWT_SECRET: your_secure_jwt_secret_here
    ports:
      - "5001:5001"

      - frontend:
    build: ./frontend
    container_name: demo-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:  